- username: codetapacademy
  title: CodeTap Academy
  description: get comfortable with JSON
- username: yourGithubUsername
  title: Your Own Crazy Title, change me
  description: try to write something between 50 and 250 characters
